Update publish-docs.yml

diff --git a/.github/workflows/publish-docs.yml b/.github/workflows/publish-docs.yml
--- a/.github/workflows/publish-docs.yml
+++ b/.github/workflows/publish-docs.yml
@@ -21,21 +21,24 @@ jobs:
     runs-on: macos-14
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-      - name: Setup Pages
-        uses: actions/configure-pages@v4
+      - uses: actions/configure-pages@v4
 
       - name: Select Xcode 16
         uses: maxim-lobanov/setup-xcode@v1
         with:
           xcode-version: '16.2.0'
 
+      - name: Pre-boot Simulator
+        run: |
+          echo "Booting iOS Simulator to avoid race conditions..."
+          xcrun simctl boot "iPhone 14" || echo "Already booted"
+          sleep 5
+
       - name: Build DocC
         run: |
           PROJECT_PATH="Helping Hand.xcodeproj"
-
           xcodebuild docbuild \
             -project "$PROJECT_PATH" \
             -scheme "Helping Hand" \
@@ -46,22 +49,20 @@ jobs:
           DOCARCHIVE_FULL_PATH=$(find /tmp/docbuild -name "$DOCARCHIVE_NAME" -print -quit)
 
           if [ -z "$DOCARCHIVE_FULL_PATH" ]; then
-              echo "Error: DocC archive '$DOCARCHIVE_NAME' not found."
-              exit 1
+            echo "Error: '$DOCARCHIVE_NAME' not found"
+            exit 1
           fi
 
-          $(xcrun --find docc) process-archive \
+          xcrun docc process-archive \
             transform-for-static-hosting "$DOCARCHIVE_FULL_PATH" \
             --output-path docs \
             --hosting-base-path 'HelpingHand'
 
-          echo "<script>window.location.href += \"/documentation/helpinghand\"</script>" > docs/index.html
+          echo '<script>window.location.href += "/documentation/helpinghand"</script>' > docs/index.html
 
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
+      - uses: actions/upload-pages-artifact@v3
         with:
           path: docs
 
       - id: deployment
-        name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
