Update publish-docs.yml

diff --git a/.github/workflows/publish-docs.yml b/.github/workflows/publish-docs.yml
--- a/.github/workflows/publish-docs.yml
+++ b/.github/workflows/publish-docs.yml
@@ -32,26 +32,26 @@ jobs:
         with:
           xcode-version: '16.2.0'
 
-      - name: Build DocC
+      - name: Build and Process DocC
         run: |
           xcodebuild docbuild \
             -project "Helping Hand.xcodeproj" \
-            -scheme "HelpingHandDocumentation" \
+            -scheme "Helping Hand" \
             -derivedDataPath /tmp/docbuild \
             -destination 'generic/platform=iOS Simulator'
 
           echo "Searching for .doccarchive in /tmp/docbuild..."
-          DOCARCHIVE_FULL_PATH=$(find /tmp/docbuild -name "*.doccarchive" -print -quit)
+          DOCARCHIVE_PATH=$(find /tmp/docbuild -name "*.doccarchive" -print -quit)
 
-          if [ -z "$DOCARCHIVE_FULL_PATH" ]; then
-              echo "Error: No .doccarchive found."
-              exit 1
+          if [ -z "$DOCARCHIVE_PATH" ]; then
+            echo "Error: No .doccarchive found."
+            exit 1
           fi
 
-          echo "Found .doccarchive at: $DOCARCHIVE_FULL_PATH"
+          echo "Found .doccarchive at: $DOCARCHIVE_PATH"
 
           xcrun docc process-archive \
-            transform-for-static-hosting "$DOCARCHIVE_FULL_PATH" \
+            transform-for-static-hosting "$DOCARCHIVE_PATH" \
             --output-path docs \
             --hosting-base-path "HelpingHand"
 
